---
version: '2'
services:
  db:
    image: postgres:13.2-alpine
    hostname: db
    container_name: postgres
    command: "postgres -c log_statement=all"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
  db-init:
    depends_on:
      - db
    image: postgres:13.2-alpine
    container_name: db-init
    command: ["sh", "-c", "export PGPASSWORD='postgres' && \
      until pg_isready -q -h db; do sleep 2; done  &&\
      psql -h db -p 5432 -U postgres postgres \
      -c \"CREATE DATABASE library;\" && \
      psql -h db -p 5432 -U postgres library \
      -c \"CREATE USER library_oltp LOGIN PASSWORD 'mostlyharmless'; \
      CREATE SCHEMA library AUTHORIZATION library_oltp;\""]