micronaut:
  application:
    name: hexagonal
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
datasources:
  default:
    schema: library
    url: jdbc:postgresql://localhost:5432/library
    driverClassName: org.postgresql.Driver
    username: library_oltp
    password: mostlyharmless
    dialect: POSTGRES
jpa:
  default:
    properties:
      hibernate:
        physical_naming_strategy: "io.micronaut.data.hibernate.naming.DefaultPhysicalNamingStrategy"
        show_sql: true
        types:
          print:
            banner=false:
    entity-scan:
      packages:
        - "com.ffr.booklibrary.inventory.core.adapters.db"
        - "com.ffr.booklibrary.circulation.core.adapters.db"
flyway:
  datasources:
    default:
      enabled: true
      locations:
        - classpath:databasemigrations
#kafka:
#  bootstrap:
#    servers: localhost:9092
#inventory:
#  kafka:
#    topic: "books"
jackson:
  serializationInclusion: ALWAYS