@startuml
' configures the library
!global $LIB_BASE_LOCATION="https://raw.githubusercontent.com/tmorin/plantuml-libs/master/dist"

' loads the library
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the eventstorming bootstrap
include('eventstorming/bootstrap')

include('eventstorming/Element/FacadeCommand')
include('eventstorming/Element/Command')
include('eventstorming/Element/Result')
include('eventstorming/Element/Event')
include('eventstorming/Element/DomainEvent')
include('eventstorming/Element/IntegrationEvent')
include('eventstorming/Element/Query')
include('eventstorming/Element/ReadModel')
include('eventstorming/Element/UserInterface')
include('eventstorming/Element/Aggregate')
include('eventstorming/Element/Service')
include('eventstorming/Element/Policy')
include('eventstorming/Element/Saga')
include('eventstorming/Element/Process')
include('eventstorming/Element/Timer')
include('eventstorming/Element/Person')
include('eventstorming/Element/System')
include('eventstorming/Element/Comment')

Command('AddBook', 'Book data added to system')
DomainEvent('BookAddedToLibrary', 'Book added to library')
Aggregate('Inventory', 'Inventory')

Command('LendBook', 'Lend a book')
Aggregate('Book', 'Book')
DomainEvent('BookLent', 'Book lent successful')
DomainEvent('BookLentFailed', 'Book lent rejected')


Command('ReturnBook', 'Reader returns a book')
DomainEvent('BookReturned', 'Book returned by user')
Aggregate('BookLending', 'Book')
AddBook->Inventory
Inventory->BookAddedToLibrary

AddBook-[hidden]d-LendBook

LendBook->Book
Book->BookLent
BookLent-[hidden]d-BookLentFailed
Book->BookLentFailed

BookLentFailed-[hidden]d-ReturnBook
LendBook-[hidden]d-ReturnBook
ReturnBook->BookLending
BookLending->BookReturned




@enduml